name: ModuS
version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: modular-api-gateway
    env_file:
      - ./api-gateway/.env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    develop:
      watch:
        - action: sync
          path: ./api-gateway/src
          target: /usr/src/app/src
        - action: rebuild
          path: ./api-gateway/package.json
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: log_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - timescale_data:/var/lib/postgresql/data
  postgres:
    image: bitnami/postgresql:17.4.0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sms
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  timescale_data:
  postgres_data: